(()=>{'use strict';
const $=s=>document.querySelector(s),DAY=86400000,dt=s=>Date.parse(s+'T00:00:00Z'),END=dt('2026-10-08')+DAY-1;
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const spans={month:{start:dt('2026-09-09'),label:'这个月',short:'近一月'},half:{start:dt('2026-04-09'),label:'这半年',short:'近半年'},year:{start:dt('2025-10-09'),label:'这一年',short:'近一年'}};
/*SHARED_DATA*/
const fmt=t=>new Date(t).toISOString().slice(0,10).replaceAll('-','.'),get=id=>stores.find(s=>s.id===id),first=id=>Math.min(...events.filter(e=>e.s===id).map(e=>e.t)),clamp=v=>Math.max(0,Math.min(1,v)),smooth=v=>(v=clamp(v),v*v*(3-2*v));
let range='month',p=0,target=0,raf=0,last=0,chapter=-1,chapters=[],rows=[],coffeeRows=[],fresh=[],again=[],total=0,uses=0,W=390,H=610,rangeLock=false,dragging=false,settleTimer=0,focusTimer=0,snapRunning=false;
/*SHARED_CITY*/
const dom=Object.fromEntries(stores.map(s=>[s.id,{el:$('#b-'+s.id),model:$('#b-'+s.id+' .model'),label:$('#b-'+s.id+' .label'),glow:$('#b-'+s.id+' .glow'),windows:[...document.querySelectorAll('#b-'+s.id+' .window')]}]));
const narrative=$('.narrative'),details=$('.detail-label'),world=$('#world');
function buildChapters(preferred=null){
 rows=events.filter(e=>e.t>=spans[range].start&&e.t<=END);const ids=[...new Set(rows.map(e=>e.s))];fresh=ids.filter(id=>first(id)>=spans[range].start);again=ids.filter(id=>!fresh.includes(id));total=rows.reduce((n,e)=>n+e.off,0);uses=rows.filter(e=>e.off>0).length;coffeeRows=rows.filter(e=>e.s==='coffee');
 const one=range==='month'?'book':range==='half'?'cinema':'noodle',three=range==='month'?'spa':'hotel';
 chapters=[
 {ids:range==='half'?['cinema','hotpot']:[one],subject:one,title:range==='month'?'熟悉的城，<br>又认识了一个新角落。':range==='half'?'电影散场，<br>这一天还没有结束。':'从一碗面，<br>认识一个新地方。',tag:range==='month'?'09.12 · 新相遇':range==='half'?'05.16 · 一个周末':'10.18 · 第一次选择'},
 {ids:['coffee'],subject:'coffee',title:'兜兜转转，<br>还是这杯熟悉的拿铁。',tag:spans[range].label+' · 又见面'},
 {ids:[three],subject:three,title:range==='month'?'这一小时，<br>把日子过慢一点。':'住进两晚远方，<br>把风景留在日常。',tag:range==='month'?'10.02 · 留给自己的片刻':'07.11 · 两晚远方'},
 {ids:[],subject:null,title:'原来，这些小事，<br>组成了我的生活。',tag:spans[range].label+' · 生活全貌'}];
 if(preferred&&!chapters.some(c=>c.subject===preferred)&&rows.some(e=>e.s===preferred)){chapters[0]={ids:[preferred],subject:preferred,title:'同一个地方，<br>换一段时间再看看。',tag:spans[range].label+' · 重新取景'};}
 chapters.forEach((c,i)=>{const s=c.subject?get(c.subject):null;const list=rows.filter(e=>c.ids.includes(e.s));c.records=list;c.quote=[...list].reverse().find(e=>e.q)?.q||'';c.money=list.reduce((n,e)=>n+e.off,0);c.uses=list.filter(e=>e.off>0).length;c.x=s?s.x:380;c.y=s?s.y:325;c.w=i===3?790:c.ids.length>1?315:145;c.name=c.ids.map(id=>get(id).name).join(' × ');if(c.ids.length>1){c.x=435;c.y=330;}c.roof=s?s.h+s.d:0;});
 $('#cafe-cups').innerHTML=coffeeRows.map((e,i)=>{const c=get('coffee'),x=c.x-30+i*8,y=c.y-19+i*2;return `<g class="cup"><path d="M${x} ${y}h5l-.5 6h-4Z" fill="#ffeec7"/><path d="M${x+5} ${y+1}q4 2 0 4" fill="none" stroke="#ffeec7"/></g>`;}).join('');
 $('#period').textContent=fmt(spans[range].start).slice(2)+' — '+fmt(END).slice(2);updateDial(Object.keys(spans).indexOf(range));chapter=-1;
}
function updateDial(v){const width=$('.dial').clientWidth-36;$('.lever').style.left=(18+width*v/2)+'px';const key=Object.keys(spans)[Math.round(v)];$('#scale-name').textContent=spans[key].short;$('#time-dial').setAttribute('aria-valuetext',spans[key].short);document.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.range===range));}
function camera(c){const vh=c.w*H/W;return{x:c.x-c.w*.52,y:c.y-vh*(c.subject?.61:.55),w:c.w,h:vh};}
function draw(){
 const index=Math.min(3,Math.floor(p*4)),u=clamp(p*4-index),c=chapters[index];
 if(chapter!==index){chapter=index;$('#kicker').textContent=c.tag+' · '+(c.name||'我的生活城');$('#title').innerHTML=c.title;$('#chapter-name').textContent=['新相遇','又见面','另一段日常','生活全貌'][index];document.querySelectorAll('.steps i').forEach((el,i)=>el.classList.toggle('active',i===index));}
 let cam=camera(c),entry=smooth(u/.2);if(index>0&&!reduce){const prev=camera(chapters[index-1]);cam={x:prev.x+(cam.x-prev.x)*entry,y:prev.y+(cam.y-prev.y)*entry,w:prev.w+(cam.w-prev.w)*entry,h:prev.h+(cam.h-prev.h)*entry};}else if(index===0&&!reduce){const grow=1+.13*(1-smooth(u/.24));cam.w*=grow;cam.h*=grow;cam.x=c.x-cam.w*.52;cam.y=c.y-cam.h*.61;}
 world.setAttribute('viewBox',`${cam.x} ${cam.y} ${cam.w} ${cam.h}`);const project=(x,y)=>({x:(x-cam.x)/cam.w*W,y:(y-cam.y)/cam.h*H});
 const base=project(c.x,c.y),roof=project(c.x,c.y-c.roof),fade=index===0?1:reduce?1:clamp(u/.16);
 const titleH=narrative.offsetHeight,titleW=narrative.offsetWidth,detailH=details.offsetHeight,detailW=details.offsetWidth;
 let titleX=Math.max(18,Math.min(W-titleW-18,roof.x-titleW*.54));let titleY=index===3?18:Math.max(12,Math.min(H*.28,roof.y-titleH-22));
 let detailX=Math.max(18,Math.min(W-detailW-18,base.x-detailW*.53));let detailY=index===3?H-165:Math.max(titleY+titleH+115,Math.min(H-detailH-13,base.y+24));detailY=Math.min(H-detailH-12,detailY);
 narrative.style.transform=`translate3d(${titleX}px,${titleY}px,0)`;narrative.style.opacity=fade;
 details.style.transform=`translate3d(${detailX}px,${detailY}px,0)`;details.style.opacity=index===3?clamp((u-.2)/.25):Math.max(.12,clamp((u-.12)/.25))*fade;
 const lx=Math.min(titleX+55,roof.x),ly=titleY+titleH+8;$('#leader').setAttribute('d',`M${lx} ${ly}V${Math.max(ly,roof.y-13)}L${roof.x} ${roof.y-7}`);$('#leader').style.opacity=index===3?0:.45*fade;$('#anchor').setAttribute('cx',roof.x);$('#anchor').setAttribute('cy',roof.y-7);$('#anchor').style.opacity=index===3?0:fade;
 if(index===3){$('#stat').textContent=`${fresh.length} 个新相遇 · ${again.length} 个熟悉的地方`;$('#quote').textContent='旧的记忆还在，新的日常接着生长。';$('#dates').textContent=`${rows.length} 条本阶段记录 · 每一处变化都有来处`;$('#benefit').textContent=`会员权益 ${uses} 次 · 实际节省 ¥${total}`;}
 else{const count=index===1?Math.min(coffeeRows.length,Math.floor(clamp((u-.15)/.45)*coffeeRows.length)):c.records.length;$('#stat').textContent=index===1?count?`${spans[range].label}，又选择了它 ${count} 次。`:'熟悉的小店，正在重新亮灯。':c.ids.length>1?'一场电影，接上一顿晚餐。':c.subject==='hotel'?'两晚住宿，一句关于风的记忆。':`这段时间，留下了 ${c.records.length} 条记录。`;$('#quote').textContent=c.quote;$('#quote').style.opacity=clamp((u-.28)/.2);$('#dates').textContent=index===1?coffeeRows.map(e=>fmt(e.t).slice(5)).join(' · ')+' · 已完成咖啡记录':c.ids.length>1?'05.16 · 15:20 电影 / 18:10 餐饮核销（记录关联）':c.records.map(e=>fmt(e.t).slice(5)+' · '+e.item).join(' / ');$('#dates').style.opacity=clamp((u-.2)/.15);$('#benefit').textContent=c.uses?`本节点 · 使用权益 ${c.uses} 次 · 省 ¥${c.money}`:'本节点没有使用会员优惠';$('#benefit').style.opacity=clamp((u-.4)/.14);}
 if(index===3){$('#quote').style.opacity=1;$('#dates').style.opacity=1;$('#benefit').style.opacity=1;}
 stores.forEach(s=>{const ci=chapters.findIndex(ch=>ch.ids.includes(s.id)),before=first(s.id)<spans[range].start;let birth=before?1:ci<0?smooth((p-.79)/.16):smooth((p*4-ci+.05)/.52);if(range==='half'&&s.id==='hotpot')birth=smooth((p*4-.18)/.44);if(reduce)birth=birth>.5?1:.2;const el=dom[s.id],selected=c.ids.includes(s.id),wide=index===3;el.el.style.opacity=birth*(selected||wide?1:.22);el.model.style.transform=`translateY(${(1-birth)*24}px) scaleY(${.07+.93*birth})`;el.label.style.opacity=wide?clamp((u-.45)/.25):0;el.glow.style.opacity=selected&&index===1?.24*smooth(u/.5):0;el.windows.forEach((w,i)=>w.setAttribute('fill',index===1&&s.id==='coffee'&&u<i/14?'#9aa586':'#ffe3a0'));el.el.style.pointerEvents=p>.96?'auto':'none';});
 document.querySelectorAll('.cup').forEach((cup,i)=>cup.style.opacity=index===1?smooth((u-.16-i*.4/Math.max(1,coffeeRows.length))/.12):0);
 const prev=index>0?chapters[index-1]:{x:c.x-80,y:c.y+50},road=$('#road');road.setAttribute('d',`M${prev.x} ${prev.y}Q${(prev.x+c.x)/2} ${Math.max(prev.y,c.y)+65} ${c.x} ${c.y+6}`);const length=road.getTotalLength();road.style.strokeDasharray=length;road.style.strokeDashoffset=length*(1-smooth(u/.4));road.style.opacity=index===3?0:.55;const point=road.getPointAtLength(length*smooth(u/.4));$('#traveler').setAttribute('cx',point.x);$('#traveler').setAttribute('cy',point.y);$('#traveler').style.opacity=index===3?0:.7;$('#connection').style.opacity=index===0&&range==='half'?clamp((u-.45)/.25):0;
 $('.end-options').hidden=p<.965;$('#skip').textContent=p>.96?'回到起点 ↖':'看全貌 ↘';$('#hint').textContent=rangeLock?'左右拨动，松手重新取景':p>.96?'回看刚才的日子，或轻点地标':u>.4&&u<.78?'停一会儿，看看自己的痕迹':'↑ 轻推继续 · ↓ 随时回看';
 $('.screen').dataset.progress=p.toFixed(4);$('.screen').dataset.node=c.subject||'overview';$('.screen').dataset.range=range;
}
function travelHeight(){return Math.max(1,$('.track').offsetHeight-$('.screen').offsetHeight);}
function readTarget(){return clamp((window.scrollY-$('.track').offsetTop)/travelHeight());}
function wake(){if(!raf)raf=requestAnimationFrame(tick);}
function tick(now){raf=0;const delta=Math.min(40,last?now-last:16);last=now;p=reduce?target:p+(target-p)*(1-Math.exp(-delta/55));if(Math.abs(p-target)<.00015)p=target;draw();if(p!==target)wake();else last=0;}
function settle(){clearTimeout(settleTimer);settleTimer=setTimeout(()=>{if(dragging||rangeLock||reduce||$('#detail').open||snapRunning)return;const actual=readTarget(),candidates=[.15,.40,.65,1],near=candidates.reduce((a,b)=>Math.abs(b-actual)<Math.abs(a-actual)?b:a);if(Math.abs(near-actual)<.026&&Math.abs(near-actual)>.003){snapRunning=true;window.scrollTo({top:$('.track').offsetTop+near*travelHeight(),behavior:'smooth'});setTimeout(()=>snapRunning=false,450);}},240);}
window.addEventListener('scroll',()=>{target=readTarget();wake();if(!snapRunning)settle();},{passive:true});
window.addEventListener('pointerdown',e=>{dragging=true;clearTimeout(settleTimer);if(snapRunning){window.scrollTo({top:window.scrollY,behavior:'instant'});snapRunning=false;}},{passive:true});window.addEventListener('pointerup',()=>{dragging=false;settle();},{passive:true});window.addEventListener('pointercancel',()=>dragging=false,{passive:true});
function go(v,immediate=false){clearTimeout(settleTimer);window.scrollTo({top:$('.track').offsetTop+v*travelHeight(),behavior:immediate||reduce?'instant':'smooth'});if(immediate){target=p=v;draw();}}
function switchRange(next){rangeLock=false;const old=chapters[Math.min(3,Math.floor(p*4))].subject,wasEnd=p>.95;range=next;buildChapters(old);let match=chapters.findIndex(c=>c.subject===old);const nextP=wasEnd?1:match>=0?(match+.6)/4:.03;$('.screen').classList.add('focusing');clearTimeout(focusTimer);focusTimer=setTimeout(()=>$('.screen').classList.remove('focusing'),180);go(nextP,true);$('#time-dial').value=Object.keys(spans).indexOf(range);}
$('#time-dial').addEventListener('input',e=>{rangeLock=true;clearTimeout(settleTimer);updateDial(+e.target.value);$('#hint').textContent='松手切换范围，保留仍有记录的当前地点';});$('#time-dial').addEventListener('change',e=>switchRange(Object.keys(spans)[Math.round(+e.target.value)]));
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>switchRange(b.dataset.range));$('#skip').onclick=()=>go(p>.96?0:1);$('#restart').onclick=()=>go(0);
function resize(){W=$('.stage').clientWidth;H=$('.stage').clientHeight;updateDial(+$('#time-dial').value);target=readTarget();p=target;draw();}new ResizeObserver(()=>{if(chapters.length)resize();}).observe($('.stage'));
document.addEventListener('keydown',e=>{if(e.target.closest('input,button,a,dialog')||$('#detail').open)return;if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(e.key)){e.preventDefault();go(e.key==='Home'?0:e.key==='End'?1:clamp(target+(['ArrowUp','PageUp'].includes(e.key)?-.12:.12)));}});
function showSummary(){clearTimeout(settleTimer);$('#dialog-label').textContent=fmt(spans[range].start)+' — '+fmt(END);$('#dialog-body').innerHTML=`<h2>每个变化，都有来处。</h2><p>${fresh.length} 个新地方 · ${again.length} 个熟悉的地方 · ${rows.length} 条有效记录。</p><div class="places">${[...new Set(rows.map(e=>e.s))].map(id=>`<button data-detail="${id}">${get(id).name}</button>`).join('')}</div><h2>会员足迹 · ¥${total}</h2>${rows.filter(e=>e.off>0).map(e=>`<div class="row"><span>${get(e.s).name}<small>${fmt(e.t)} · ${e.item}</small></span><span>¥${e.off}</span></div>`).join('')}<p><a href="./stroll.html">滑动生长版</a> · <a href="./journey.html">时间总览版</a> · <a href="./index.html">初版</a></p><small>虚构示例，统计已使用会员优惠，不包含未使用券面额。按主题组织，不代表时间连续或实际到访路线。</small>`;if(!$('#detail').open)$('#detail').showModal();}
function showPlace(id){clearTimeout(settleTimer);const s=get(id),list=rows.filter(e=>e.s===id),q=[...list].reverse().find(e=>e.q);$('#dialog-label').textContent=spans[range].label+' · '+s.name;$('#dialog-body').innerHTML=`<h2>${s.name}</h2><p>这一阶段 ${list.length} 条记录，过去的记忆也依然保留。</p>${q?`<div class="quote">${q.q}</div>`:''}${list.map(e=>`<div class="row"><span>${e.item}<small>${fmt(e.t)}</small></span><span>${e.off?'省 ¥'+e.off:''}</span></div>`).join('')}<div class="places"><button id="summary-back">回到本阶段依据</button></div>`;if(!$('#detail').open)$('#detail').showModal();}
$('#facts').onclick=showSummary;$('.close').onclick=()=>$('#detail').close();document.addEventListener('click',e=>{const el=e.target.closest('[data-detail]'),building=e.target.closest('[data-place]');if(el)showPlace(el.dataset.detail);else if(building&&p>.96)showPlace(building.dataset.place);if(e.target.closest('#summary-back'))showSummary();});$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')&&e.clientY<$('#detail').getBoundingClientRect().top)$('#detail').close();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(settleTimer);cancelAnimationFrame(raf);raf=0;last=0;}else{target=readTarget();wake();}});
buildChapters();resize();
})();
